# Generated by Django 3.1.2 on 2020-10-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pb_date',
            new_name='pub_date',
        ),
    ]
